name: Deploy
on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: wasm32-unknown-unknown

      - name: Install trunk
        uses: jetli/trunk-action@v0.1.0
      - name: Install wasm-bindgen
        uses: jetli/wasm-bindgen-action@v0.1.0

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: trunk build --release --public-url "${GITHUB_REPOSITORY#*/}"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: dist
